language: c

compiler: gcc

install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - curl -LO "http://ftp.postgresql.org/pub/snapshot/${PGVERSION}/postgresql${FTPPATH}-snapshot.tar.bz2"
  - mkdir postgresql-${PGVERSION}
  - tar jxf postgresql${FTPPATH}-snapshot.tar.bz2 -C postgresql-${PGVERSION} --strip-components 1
  - pushd postgresql-${PGVERSION}
  - CFLAGS=-O0 ./configure && make > /dev/null && sudo make install > /dev/null
  - popd
  - echo "override CFLAGS += -Werror" >> Makefile
  - PATH=/usr/local/pgsql/bin:$PATH pg_config

env:
  matrix:
    - PGVERSION=dev FTPPATH=""
    - PGVERSION=9.3 FTPPATH="-9.3"
    - PGVERSION=9.2 FTPPATH="-9.2"

script: PATH=/usr/local/pgsql/bin:$PATH make
