language: c

compiler: gcc

install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - cd
  - curl -LO "http://ftp.postgresql.org/pub/snapshot/${PGVERSION}/postgresql${FTPPATH}-snapshot.tar.bz2"
  - mkdir postgresql-${PGVERSION}
  - tar jxf postgresql${FTPPATH}-snapshot.tar.bz2 -C postgresql-${PGVERSION} --strip-components 1
  - pushd postgresql-${PGVERSION}
  - CFLAGS=-O0 ./configure && make > /dev/null && sudo make install > /dev/null
  - popd
  - echo "override CFLAGS += -Werror" >> Makefile
  - PATH=/usr/local/pgsql/bin:$PATH pg_config
  - mv ${TRAVIS_BUILD_DIR} postgresql-${PGVERSION}/contrib/pgcov
  - cd postgresql-${PGVERSION}/contrib/pgcov

env:
  matrix:
    - PGVERSION=12 FTPPATH="-12"
    - PGVERSION=11 FTPPATH="-11"
    - PGVERSION=10 FTPPATH="-10"
    - PGVERSION=9.6 FTPPATH="-9.6"
    - PGVERSION=9.5 FTPPATH="-9.5"
    - PGVERSION=9.4 FTPPATH="-9.4"
    - PGVERSION=9.3 FTPPATH="-9.3"
    - PGVERSION=9.2 FTPPATH="-9.2"
    - PGVERSION=9.1 FTPPATH="-9.1" NO_PGXS=1

script: PATH=/usr/local/pgsql/bin:$PATH make
